
@baseUrl = http://localhost:19870
@contentType = application/json


### 自己的组织列表

# * @apiParam {String} [type='Group'] Group 为组，null为个人组，都被认为是命名空间
# * @apiParam {String} [username] 用户名，不传递默认为自己

GET {{baseUrl}}/api/user/orgs
Content-Type: {{contentType}}

### 用户项目列表

@username = admin

# @apiSuccess {Number} count 总条数.
# @apiSuccess {Number} [limit=10] 每页显示多少条.
# @apiSuccess {Number} [page=1] 弟几页.
# @apiSuccess {Number} [pages] 总页数.

GET {{baseUrl}}/api/users/{{username}}/repos?page=1&limit=2
Content-Type: {{contentType}}

### 获取项目详情

@repo = test

# @apiSuccess {String} username 用户名
# @apiSuccess {String} repo 仓名称

GET {{baseUrl}}/api/repos/{{username}}/{{repo}}
Content-Type: {{contentType}}

### 项目文件列表

@id = 13

# @apiParam {String} id 项目ID
# @apiParam {String} [path] 存储库中的路径
# @apiParam {String} [ref] 存储库分支或标记的名称，如果没有给出默认分支
# @apiParam {String} [recursive] 用于获取递归树的布尔值（默认为false）

GET {{baseUrl}}/api/repos/{{id}}/tree
Content-Type: {{contentType}}

# @apiSuccess {String} readmeContent 返回 README.md 内容
# @apiSuccess sha 7eb9d6bbf8ef2f3236f0e71dd8e020715507ea01
# @apiSuccess summary 提交commit内容 "Add repo tree API parameter path."
# @apiSuccess message 提交commit内容 "Add repo tree API parameter path.\n"
# @apiSuccess messageRaw 提交commit内容 "Add repo tree API parameter path.\n"
# @apiSuccess owner 返回 { "name": "jaywcjlove", "email": "398188662@qq.com" }
# @apiSuccess amend
# @apiSuccess time 535736727
# @apiSuccess date 2018-08-31T17:32:07.000Z"
# @apiSuccess timeMs 535736727000
# @apiSuccess timeOffset 80
# @apiSuccess isFile alse
# @apiSuccess path 返回路径
# @apiSuccess entryCount



### 获取 README

GET {{baseUrl}}/api/repos/{{username}}/{{repo}}/readme
Content-Type: {{contentType}}


### 获取文件详情

@ref = master
# @filepath = conf/sequelize.js
@filepath = README.md
@repo2 = gitke

# http://localhost:19870/admin/gitke/blob/master/conf/conf.js
GET {{baseUrl}}/api/repos/{{username}}/{{repo2}}/blob/{{ref}}/{{filepath}}
Content-Type: {{contentType}}

### 获取文件内容

# http://localhost:19870/admin/gitke/raw/master/conf/conf.js
# /:owner/:repo/raw/:ref/*

GET {{baseUrl}}/{{username}}/{{repo2}}/raw/{{ref}}/{{filepath}}

### Add Repo

POST {{baseUrl}}/api/user/repos
Content-Type: {{contentType}}

{
	"name": "test",
	"description": ""
}

### Remove Repo

@repoTest = test

DELETE {{baseUrl}}/api/repos/{{username}}/{{repoTest}}
